---
  # Install packages
  - name: Install EPEL repository
    yum:
      name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present
    when: ansible_distribution == "CentOS"
  - name: Install Gluster yum repository
    yum:
      name: centos-release-gluster
      state: latest
    when: ansible_distribution == "CentOS"
  - name: Install glusterfs-server package
    yum:
      name: glusterfs-server
      state: latest
    when: ansible_distribution == "CentOS"
  - name: Install glusterfs-server package
    apt:
      name: glusterfs-server
      update_cache: yes
      state: latest
    when: ansible_os_family == 'Debian'
  - name: Install nfs-common package
    apt:
      name: nfs-common
      state: latest
    when: ansible_os_family == 'Debian'
