---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Configure Cluster Network"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - kubeconfig
      - network-environment
      - calico
