---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Install Docker"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    roles:
      - docker
      - role: docker-registry-cert
        when: use_private_docker_registry is defined and use_private_docker_registry|bool == true
