---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "Install Kubernetes Kubelet"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml
    roles:
      - network-environment
      - kubeconfig
      - kubelet
